# This workflow will launch at 00:00 every day
name: RDF Tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rdf-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install junit2md
        uses: actions-rs/install@v0.1
        with:
          crate: junit2md
          version: 0.1.0
      - name: Update submodules
        run: git submodule init && git submodule update
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run RDF tests
        run: sbt "bellman-rdf-tests/test" || true
      - name: Convert Junit XML to Markdown
        run: ~/.cargo/bin/junit2md modules/rdf-tests/target/test-reports/TEST-com.gsk.kg.engine.RdfTests.xml > rdf-test-results.md
      - name: Create Pull Request
        if: env.NO_CHANGES == null
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          path: master
          commit-message: Update rdf-test-results.md
          title: Update rdf-test-results.md
          branch: auto-update-rdf-test-results
          body: |
            > ❕This is an automated PR generated by rdf-tests.yml
            # What has been done in this PR?
            Update rdf-test-results.md
      - name: Show Pull Request URL
        if: env.PULL_REQUEST_NUMBER != null
        run: 'echo "Pull-request created: https://github.com/gsk-aiops/bellman/pull/${{ env.PULL_REQUEST_NUMBER }}"'
