# This workflow will launch at 00:00 every day
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rdf-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run RDF tests
        run: sbt "bellman-rdf-tests/test"
