name: Scala CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v2.1.4
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run checks
        run: sbt ci-test
      - name: Automerge Scala Steward PRs
        if: success() && github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Scala Steward')
        uses: ridedott/merge-me-action@v2.2.13
        with:
          GITHUB_LOGIN: github-actions[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dependabot Merge
        if: success()
        uses: ridedott/merge-me-action@v2.2.13
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
